title: TantraLab
logo: assets/images/logo.png
theme: minima
show_downloads: false
navigation:
  - Home: /
  - People: /people
  - Research: /research
  - Publications: /publications
  - Contact: /contact
